name: Deploy Frontend Docker Image

on:
  push:
    branches:
      - main
      - dev
    paths:
      - "apps/frontend/**"
      - "packages/config/**"
      - "packages/types/**"
  workflow_dispatch:

jobs:
  deploy_image:
    name: Deploy Docker Image to Registry
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.IMAGE_REPO }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set ENV
        id: set-env
        run: |
          if [ "${{ github.ref_name }}" = "main" ]; then
            echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.MAIN_NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> "$GITHUB_OUTPUT"
            echo "NEXT_PUBLIC_API_URL=${{ secrets.MAIN_NEXT_PUBLIC_API_URL }}" >> "$GITHUB_OUTPUT"
            echo "NEXT_PUBLIC_SOCKET_BASE_URL=${{ secrets.MAIN_NEXT_PUBLIC_SOCKET_BASE_URL }}" >> "$GITHUB_OUTPUT"
          elif [ "${{ github.ref_name }}" = "dev" ]; then
            echo "NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ secrets.DEV_NEXT_PUBLIC_GOOGLE_CLIENT_ID }}" >> "$GITHUB_OUTPUT"
            echo "NEXT_PUBLIC_API_URL=${{ secrets.DEV_NEXT_PUBLIC_API_URL }}" >> "$GITHUB_OUTPUT"
            echo "NEXT_PUBLIC_SOCKET_BASE_URL=${{ secrets.DEV_NEXT_PUBLIC_SOCKET_BASE_URL }}" >> "$GITHUB_OUTPUT"
          fi

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          build-args: |
            NEXT_PUBLIC_GOOGLE_CLIENT_ID=${{ steps.set-env.outputs.NEXT_PUBLIC_GOOGLE_CLIENT_ID }}
            NEXT_PUBLIC_API_URL=${{ steps.set-env.outputs.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_SOCKET_BASE_URL=${{ steps.set-env.outputs.NEXT_PUBLIC_SOCKET_BASE_URL }}
          file: Dockerfile.frontend
          push: true
          tags: ${{ secrets.IMAGE_REPO }}/${{ secrets.REGISTRY_USERNAME }}/app-frontend-${{ github.ref_name }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
